#!/bin/bash
/bin/sed -e 's_\(<description>.*\)\(http://[^< ]*\)\(.*</description>\)_\1\&lt;a href=\&quot;\2\&quot;\&gt;\2\&lt;/a\&gt;\3_g' -e 's_\(<description>.*\)@\([a-zA-Z0-9_]*\)\(.*</description>\)_\1\&lt;a href=\&quot;http://twitter.com/\2\&quot;\&gt;@\2\&lt;/a\&gt;\3_g' -e 's_ #\([a-zA-Z0-9_&#;]*\)_ \&lt;a href=\&quot;http://search.twitter.com/search?q=%23\1\&quot;\&gt;#\1\&lt;/a\&gt;_g'
